### ISSUE TITLE
Doubt regarding the coordinates entered

### ISSUE THREAD

**Issue by amalthomas-exe** [Aditi-Asati/online-class-bot#4]
@Aditi-Asati 
How did you manage to get the coordinates of the buttons, as in :
`p.click(530, 281)`

**Comment by shravanasati** [comment]
The coordinates of the mouse cursor on the screen can be known using the following piece of code:
```
from time import sleep
import pyautogui
for _ in range(10):
    print(pyautogui.position())
    sleep(1)
```

**Comment by amalthomas-exe** [comment]
@Shravan-1908 thanks for your response. but the same can be done as:
`import pyautogui`
`pyautogui.mouseInfo()`

This will launch a tkinter windows which show the real time position of the mouse cursor.

**Comment by shravanasati** [comment]
Didn't knew that such thing existed. Much convenient than what I answered. Thanks @amalthomas-exe.
